package com.roy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseArticle<M extends BaseArticle<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setAliasTitle(java.lang.String aliasTitle) {
		set("alias_title", aliasTitle);
		return (M)this;
	}
	
	public java.lang.String getAliasTitle() {
		return getStr("alias_title");
	}

	public M setAuthor(java.lang.String author) {
		set("author", author);
		return (M)this;
	}
	
	public java.lang.String getAuthor() {
		return getStr("author");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setClassifyId(java.lang.Long classifyId) {
		set("classify_id", classifyId);
		return (M)this;
	}
	
	public java.lang.Long getClassifyId() {
		return getLong("classify_id");
	}

	public M setSourceName(java.lang.String sourceName) {
		set("source_name", sourceName);
		return (M)this;
	}
	
	public java.lang.String getSourceName() {
		return getStr("source_name");
	}

	public M setSourceUrl(java.lang.String sourceUrl) {
		set("source_url", sourceUrl);
		return (M)this;
	}
	
	public java.lang.String getSourceUrl() {
		return getStr("source_url");
	}

	public M setSummary(java.lang.String summary) {
		set("summary", summary);
		return (M)this;
	}
	
	public java.lang.String getSummary() {
		return getStr("summary");
	}

	public M setKeywords(java.lang.String keywords) {
		set("keywords", keywords);
		return (M)this;
	}
	
	public java.lang.String getKeywords() {
		return getStr("keywords");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setIsHot(java.lang.Integer isHot) {
		set("is_hot", isHot);
		return (M)this;
	}
	
	public java.lang.Integer getIsHot() {
		return getInt("is_hot");
	}

	public M setPic(java.lang.String pic) {
		set("pic", pic);
		return (M)this;
	}
	
	public java.lang.String getPic() {
		return getStr("pic");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
