package com.roy.model;

import com.roy.model.base.BaseClassify;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Classify extends BaseClassify<Classify> {
	public static final Classify dao = new Classify().dao();
	private List<Classify> children;        //子菜单

	public List<Classify> getChildren() {
		return children;
	}

	public void setChildren(List<Classify> children) {
		this.children = children;
	}
}
