package com.roy.model;

import com.roy.model.base.BaseClassify;

import java.util.List;
import java.util.Map;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Classify extends BaseClassify<Classify> {
	public static final Classify dao = new Classify().dao();

	private List<Classify> children;        //子菜单

	public List<Classify> getChildren() {
		return children;
	}

	public void setChildren(List<Classify> children) {
		this.children = children;
	}
	@Override
	protected Map<String, Object> _getAttrs() {
		Map<String, Object> attrs = super._getAttrs();
		attrs.put("children", this.children);
		return attrs;
	}
    public String toString() {
        return "Classify{"+
                "id:" + this.getId() + ", "+"name:" + this.getName() +
                ", "+"alias_name:" + this.getAliasName() +", "+"seq:" + this.getSeq()+
                ", "+"pid:" + this.getPid() +", "+"children:" + this.getChildren()
                +"}";
    }
}
